### ISSUE TITLE
Sesion 1:1 Feedback Trainers Andres

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#30]
Enviar Programacion 1:1 31 enero

**Comment by tablerodetrabajo** [comment]
1:1 Juan Guerrero no sabe cuales son sus tareas.

**Comment by tablerodetrabajo** [comment]
Ingrid Ramos: receptiva feedback ok.  TOF: 71%

**Comment by Andres-Bueno** [comment]
Se completó 1:1 con Pablo Ramos hoy. Tarea completa
