### ISSUE TITLE
Entrenamiento Mentores Andres

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#33]
Enero 31 enviar listado Y CRONOGRAMA DE CAPACITACION

**Comment by Andres-Bueno** [comment]
Listo el cronograma de capacitación. Tarea completa!

**Comment by tablerodetrabajo** [comment]
Due Date, Sabado 11 de Feb

**Comment by tablerodetrabajo** [comment]
No se completo, training mentores, se completara la ultima sesion feb 15 2 p.m.

**Comment by Andres-Bueno** [comment]
Completada hoy!
