### ISSUE TITLE
Calibracion trainers agenda nesting Graciela /andres

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#34]
Enero 31 enviar cronograma capacitacion trainers

**Comment by Andres-Bueno** [comment]
Hoy se socializo la agenda con los trainers durante la reunion del team meeting. Se establecieron los POCs por cada LOB, se da inicio al trabajo de generar las agendas para New hire y una vez estén completas, calibrar la agenda para nesting.
