### ISSUE TITLE
Reunion Semanal revision QA y ACCM Andres

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#36]
31 enero enviar cronograma

**Comment by tablerodetrabajo** [comment]
Reunión jose lopez. generar acta.
Distribución de Mentors no es el adecuado 
Semana 1 1:5  PENDIENTE VERIFICACION RATIOS MENTORS

**Comment by Andres-Bueno** [comment]
Semana 1 ratio mentors 1:5
Semana 2 ratio mentors 1:7
Semana 3 ratio mentors 1:6

Invitaciones enviadas para el ACCM y el QA Manager.
