### ISSUE TITLE
Revisión y modificación agenda Nesting ANDRES

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#37]
Enviar programación de reuniones modificación nesting

**Comment by Andres-Bueno** [comment]
Se envía correo con feedback de agenda de nesting a Graciela. Se reprograma reunión con ella.

**Comment by Andres-Bueno** [comment]
Se tuvo la reunión con Graciela al respecto, además se solicito una cuenta de EXT para que ella pueda acceder a nuestro shared drive. Hicimos un pequeño cambio en la agenda ya; sin embargo la actualizacion restante tendrá que seguir en progreso, pero podemos mover la tarea a completo.

**Comment by tablerodetrabajo** [comment]
Due date,  Jueves 9 de febrero
