### ISSUE TITLE
TOF Semana 2

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#46]
Ingrid Ramos
Juan Guerrero
Natalie Bohorquez
Pablo Ramos
Hernan Martinez

**Comment by Andres-Bueno** [comment]
Ingrid Ramos, Juan Guerrero - Completo

**Comment by Andres-Bueno** [comment]
Hernan Martinez

**Comment by Andres-Bueno** [comment]
Pablo Ramos
