### ISSUE TITLE
Knowledge Test- Analisis y plan de accion

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#5]
Creación reporte final de KT, entrega de accion plan y seguimiento.
Feb 22 Entrega reporte y action plan
Feb 23 a Marzo 5 action plan

ANDRES

**Comment by Andres-Bueno** [comment]
Se envió correo a producción. Se obtiene un soporte por parte de ellos para hacer seguimiento

**Comment by tablerodetrabajo** [comment]
Andres, cual es el plan de acción que se dio a la operación y cuando se compartieron los resultados de knowledge test a la operacion?
