### ISSUE TITLE
Nuevas Directrices de Nesting/Andres

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#60]

**Comment by tablerodetrabajo** [comment]
Feb 14 reunion con ACCm nesting, dos propuestas, pendiente reunirse con director.

**Comment by tablerodetrabajo** [comment]
Asignar mentors por cada LOB para que entren a entrenamiento semana de el 20 de Feb. Propuesta se cierra jueves 16 feb. programacion reunion diana siguiente semana.

**Comment by Andres-Bueno** [comment]
Diana ha pospuesto la reunión de hoy. El plan se le va a presentar a la brevedad posible

**Comment by Andres-Bueno** [comment]
Hoy me confirmaron que con el ascenso de Diana a directora, aún no se sabe quién quedaría encargado de nesting.
