### ISSUE TITLE
Verificar salarios Trainers/Andres

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#62]

**Comment by Andres-Bueno** [comment]
Se ha enviado correo a Maria del Pilar para ver cómo nos puede ayudar. Estamos a la espera de su respuesta.

**Comment by Andres-Bueno** [comment]
Se escaló con el Generalista de Rebel, Juan Aguilera

**Comment by tablerodetrabajo** [comment]
Ir a oficina de Maria del Pilar para verificar y solucionar este tema. Due date feb 20
