### ISSUE TITLE
Plan Seguimiento Trainers con Low Csat ANDRES

### ISSUE THREAD

**Issue by tablerodetrabajo** [tablerodetrabajo/Rebel-Febrero#65]
Guerrero, Paola - 0460
Gualteros, Brandon - 9110
Sabogal, Wendi - 6808
Cuello, Jaime - 3868
Olarte, Ivan - 4425

**Comment by Andres-Bueno** [comment]
Hacerlos responsables de su propio CSAT y que encuentren análisis de causa raiz.
